### ISSUE TITLE
reg_inhomogeneity issue

### ISSUE THREAD

**Issue by ManuelSpinola** [Nowosad/regional#6]
When I try the función regional_inhomogeneity I have the following error message:

uf_aclap$inh = reg_inhomogeneity(uf_aclap, s_presente_cla, sample_size = 1)

Error: Your input vector stores NA values...

These are the files:

[
](https://1drv.ms/f/s!AmkQxwG61-VIlOdODVIG5IX9zn9KyQ?e=ahcTZ8)

**Comment by ManuelSpinola** [comment]
https://1drv.ms/f/s!AmkQxwG61-VIlOdODVIG5IX9zn9KyQ?e=kK1d6g

**Comment by Nowosad** [comment]
The current (GitHub) version of the package seems to be working fine. I plan to submit it to CRAN soon.

``` r
library(regional)
library(sf)
#> Linking to GEOS 3.12.1, GDAL 3.7.3, PROJ 9.2.1; sf_use_s2() is TRUE
library(terra)
#> terra 1.7.76

uf_aclap = read_sf("uf_aclap.gpkg")
s_presente_cla = rast("s_presente_cla.tif")

plot(s_presente_cla)
plot(uf_aclap[0], add = TRUE, border = "red")
```

![](https://i.imgur.com/khWbkU8.png)

``` r

uf_aclap$inh = reg_inhomogeneity(uf_aclap, s_presente_cla, sample_size = 30, na.rm = TRUE)
uf_aclap$inh
#>  [1] 0.7218391 1.5609195 1.0804598 1.0804598 1.5586207 0.6367816 1.4666667
#>  [8] 0.8942529 1.0000000 0.7287356
```

**Comment by ManuelSpinola** [comment]
Thank you very much.
